/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home_package;


import AppPackage.AnimationClass;
import Mp3Widget.MP3PlayerGUI;
import java.awt.Color;
import java.awt.TrayIcon;
import widgetlauncher.Main;
/**
 *
 * @author Guest
 */
public class Apps extends javax.swing.JFrame {

    DisplayTrayIcon dwt = new DisplayTrayIcon();
   int page=0;
    
    AnimationClass gif = new AnimationClass();
    public Apps() {
        initComponents();
       
        
        clock clo = new clock();
        clo.time(time_1,jLabel1);
       
    
      
    }
 



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        about = new javax.swing.JLabel();
        aboutDev = new javax.swing.JLabel();
        credit = new javax.swing.JLabel();
        version = new javax.swing.JLabel();
        help = new javax.swing.JLabel();
        history = new javax.swing.JLabel();
        history_3 = new javax.swing.JLabel();
        history_4 = new javax.swing.JLabel();
        history_1 = new javax.swing.JLabel();
        history_2 = new javax.swing.JLabel();
        convertor = new javax.swing.JLabel();
        memo = new javax.swing.JLabel();
        timer = new javax.swing.JLabel();
        stopwatch = new javax.swing.JLabel();
        calculator = new javax.swing.JLabel();
        time_1 = new javax.swing.JLabel();
        titleBar = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        background1 = new javax.swing.JLabel();
        background2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(890, 530));
        setMinimumSize(new java.awt.Dimension(890, 530));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(890, 530));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutMouseEntered(evt);
            }
        });
        getContentPane().add(about);
        about.setBounds(220, 0, 110, 40);

        aboutDev.setBackground(java.awt.Color.darkGray);
        aboutDev.setFont(new java.awt.Font("DS-Digital", 0, 12)); // NOI18N
        aboutDev.setForeground(new java.awt.Color(0, 168, 255));
        aboutDev.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutDev.setText("developers");
        aboutDev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutDev.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        aboutDev.setOpaque(true);
        aboutDev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutDevMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutDevMouseExited(evt);
            }
        });
        getContentPane().add(aboutDev);
        aboutDev.setBounds(220, 40, 130, 30);

        credit.setBackground(java.awt.Color.darkGray);
        credit.setFont(new java.awt.Font("DS-Digital", 0, 12)); // NOI18N
        credit.setForeground(new java.awt.Color(0, 168, 255));
        credit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        credit.setText("credits");
        credit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        credit.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        credit.setOpaque(true);
        credit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                creditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                creditMouseExited(evt);
            }
        });
        getContentPane().add(credit);
        credit.setBounds(220, 70, 130, 30);

        version.setBackground(java.awt.Color.darkGray);
        version.setFont(new java.awt.Font("DS-Digital", 0, 12)); // NOI18N
        version.setForeground(new java.awt.Color(0, 168, 255));
        version.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        version.setText("version");
        version.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        version.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        version.setOpaque(true);
        version.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                versionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                versionMouseExited(evt);
            }
        });
        getContentPane().add(version);
        version.setBounds(220, 100, 130, 30);

        help.setBackground(java.awt.Color.darkGray);
        help.setFont(new java.awt.Font("DS-Digital", 0, 12)); // NOI18N
        help.setForeground(new java.awt.Color(0, 168, 255));
        help.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        help.setText("help");
        help.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        help.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        help.setOpaque(true);
        help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                helpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                helpMouseExited(evt);
            }
        });
        getContentPane().add(help);
        help.setBounds(220, 130, 130, 30);

        history.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                historyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                historyMouseExited(evt);
            }
        });
        getContentPane().add(history);
        history.setBounds(70, 0, 110, 40);

        history_3.setBackground(java.awt.Color.darkGray);
        history_3.setFont(new java.awt.Font("DS-Digital", 0, 12)); // NOI18N
        history_3.setForeground(new java.awt.Color(0, 168, 255));
        history_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        history_3.setText("<No History>");
        history_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        history_3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        history_3.setOpaque(true);
        history_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                history_3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                history_3MouseExited(evt);
            }
        });
        getContentPane().add(history_3);
        history_3.setBounds(80, 100, 130, 30);

        history_4.setBackground(java.awt.Color.darkGray);
        history_4.setFont(new java.awt.Font("DS-Digital", 0, 12)); // NOI18N
        history_4.setForeground(new java.awt.Color(0, 168, 255));
        history_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        history_4.setText("Complete History");
        history_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        history_4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        history_4.setOpaque(true);
        history_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                history_4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                history_4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                history_4MouseExited(evt);
            }
        });
        getContentPane().add(history_4);
        history_4.setBounds(80, 130, 130, 30);

        history_1.setBackground(java.awt.Color.darkGray);
        history_1.setFont(new java.awt.Font("DS-Digital", 0, 12)); // NOI18N
        history_1.setForeground(new java.awt.Color(0, 168, 255));
        history_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        history_1.setText("<No History>");
        history_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        history_1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        history_1.setOpaque(true);
        history_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                history_1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                history_1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                history_1MouseExited(evt);
            }
        });
        getContentPane().add(history_1);
        history_1.setBounds(80, 40, 130, 30);

        history_2.setBackground(java.awt.Color.darkGray);
        history_2.setFont(new java.awt.Font("DS-Digital", 0, 12)); // NOI18N
        history_2.setForeground(new java.awt.Color(0, 168, 255));
        history_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        history_2.setText("<No History>");
        history_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        history_2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        history_2.setOpaque(true);
        history_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                history_2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                history_2MouseExited(evt);
            }
        });
        getContentPane().add(history_2);
        history_2.setBounds(80, 70, 130, 30);

        convertor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        convertor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                convertorMouseClicked(evt);
            }
        });
        getContentPane().add(convertor);
        convertor.setBounds(140, 290, 190, 140);

        memo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        memo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                memoMouseClicked(evt);
            }
        });
        getContentPane().add(memo);
        memo.setBounds(350, 140, 180, 130);

        timer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        timer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timerMouseClicked(evt);
            }
        });
        getContentPane().add(timer);
        timer.setBounds(350, 290, 180, 140);

        stopwatch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stopwatch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stopwatchMouseClicked(evt);
            }
        });
        getContentPane().add(stopwatch);
        stopwatch.setBounds(550, 130, 180, 300);

        calculator.setForeground(new java.awt.Color(0, 168, 255));
        calculator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calculator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calculatorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                calculatorMouseEntered(evt);
            }
        });
        getContentPane().add(calculator);
        calculator.setBounds(140, 140, 190, 130);

        time_1.setBackground(new java.awt.Color(0, 0, 0));
        time_1.setFont(new java.awt.Font("DS-Digital", 1, 14)); // NOI18N
        time_1.setForeground(new java.awt.Color(0, 168, 255));
        time_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time_1.setOpaque(true);
        getContentPane().add(time_1);
        time_1.setBounds(730, 500, 160, 30);

        titleBar.setBackground(new java.awt.Color(0, 0, 0));
        titleBar.setFont(new java.awt.Font("DS-Digital", 1, 18)); // NOI18N
        titleBar.setForeground(new java.awt.Color(0, 168, 255));
        titleBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleBar.setText("Next Page");
        titleBar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        titleBar.setOpaque(true);
        titleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titleBarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                titleBarMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleBarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                titleBarMouseReleased(evt);
            }
        });
        getContentPane().add(titleBar);
        titleBar.setBounds(60, 500, 180, 30);

        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        getContentPane().add(close);
        close.setBounds(820, 10, 30, 20);

        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize);
        minimize.setBounds(760, 10, 40, 20);

        background.setFont(new java.awt.Font("DS-Digital", 0, 12)); // NOI18N
        background.setForeground(new java.awt.Color(0, 168, 255));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home_package/DIFF.jpg.png"))); // NOI18N
        background.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        background.setMaximumSize(new java.awt.Dimension(800, 600));
        background.setMinimumSize(new java.awt.Dimension(800, 600));
        background.setPreferredSize(new java.awt.Dimension(800, 600));
        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backgroundMouseEntered(evt);
            }
        });
        getContentPane().add(background);
        background.setBounds(0, 0, 890, 530);

        background1.setFont(new java.awt.Font("DS-Digital", 0, 12)); // NOI18N
        background1.setForeground(new java.awt.Color(0, 168, 255));
        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home_package/diff2.png"))); // NOI18N
        background1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        background1.setMaximumSize(new java.awt.Dimension(800, 600));
        background1.setMinimumSize(new java.awt.Dimension(800, 600));
        background1.setPreferredSize(new java.awt.Dimension(800, 600));
        background1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                background1MouseEntered(evt);
            }
        });
        getContentPane().add(background1);
        background1.setBounds(890, 0, 890, 530);

        background2.setBackground(new java.awt.Color(0, 0, 0));
        background2.setFont(new java.awt.Font("DS-Digital", 0, 12)); // NOI18N
        background2.setForeground(new java.awt.Color(0, 168, 255));
        background2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        background2.setMaximumSize(new java.awt.Dimension(800, 600));
        background2.setMinimumSize(new java.awt.Dimension(800, 600));
        background2.setOpaque(true);
        background2.setPreferredSize(new java.awt.Dimension(800, 600));
        background2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                background2MouseEntered(evt);
            }
        });
        getContentPane().add(background2);
        background2.setBounds(0, 0, 890, 530);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
  
   history obj = new history("Applications");
   obj.addHistory();
   History_set god = new History_set();
   god.setHistory(history_1,history_2,history_3);
   history_1.setVisible(false);
   history_2.setVisible(false);
   history_3.setVisible(false);
   history_4.setVisible(false);
    aboutDev.setVisible(false);
   credit.setVisible(false);
   version.setVisible(false);
   help.setVisible(false);
  
  
   
    }//GEN-LAST:event_formWindowOpened

    private void calculatorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculatorMouseEntered
      
    }//GEN-LAST:event_calculatorMouseEntered

    private void history_1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_history_1MouseEntered
    history_1.setBackground(Color.BLACK);
    }//GEN-LAST:event_history_1MouseEntered

    private void history_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_history_1MouseExited
     history_1.setBackground(Color.DARK_GRAY);
     
    }//GEN-LAST:event_history_1MouseExited

    private void history_2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_history_2MouseEntered
        history_2.setBackground(Color.BLACK);
    }//GEN-LAST:event_history_2MouseEntered

    private void history_3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_history_3MouseEntered
history_3.setBackground(Color.BLACK);        // TODO add your handling code here:
    }//GEN-LAST:event_history_3MouseEntered

    private void history_4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_history_4MouseEntered
        history_4.setBackground(Color.BLACK);
    }//GEN-LAST:event_history_4MouseEntered

    private void history_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_history_2MouseExited
 history_2.setBackground(Color.DARK_GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_history_2MouseExited

    private void history_3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_history_3MouseExited
history_3.setBackground(Color.DARK_GRAY);         // TODO add your handling code here:
    }//GEN-LAST:event_history_3MouseExited

    private void history_4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_history_4MouseExited
history_4.setBackground(Color.DARK_GRAY);         // TODO add your handling code here:
    }//GEN-LAST:event_history_4MouseExited

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
    this.hide();
    }//GEN-LAST:event_closeMouseClicked

    private void aboutDevMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutDevMouseEntered
       aboutDev.setBackground(Color.BLACK);
    }//GEN-LAST:event_aboutDevMouseEntered

    private void aboutDevMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutDevMouseExited
         aboutDev.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_aboutDevMouseExited

    private void creditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditMouseEntered
          credit.setBackground(Color.BLACK);
    }//GEN-LAST:event_creditMouseEntered

    private void creditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditMouseExited
      credit.setBackground(Color.DARK_GRAY);  // TODO add your handling code here:
    }//GEN-LAST:event_creditMouseExited

    private void versionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_versionMouseEntered
        version.setBackground(Color.BLACK);
    }//GEN-LAST:event_versionMouseEntered

    private void versionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_versionMouseExited
      version.setBackground(Color.DARK_GRAY);  // TODO add your handling code here:
    }//GEN-LAST:event_versionMouseExited

    private void helpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMouseEntered
      help.setBackground(Color.BLACK);  // TODO add your handling code here:
    }//GEN-LAST:event_helpMouseEntered

    private void helpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMouseExited
      help.setBackground(Color.DARK_GRAY);  // TODO add your handling code here:
    }//GEN-LAST:event_helpMouseExited

    private void backgroundMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseEntered
        history_1.setVisible(false);
        history_2.setVisible(false);
        history_3.setVisible(false);
        history_4.setVisible(false);
        aboutDev.setVisible(false);
        credit.setVisible(false);
        version.setVisible(false);
        help.setVisible(false);
    }//GEN-LAST:event_backgroundMouseEntered

    private void titleBarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBarMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_titleBarMouseReleased

    private void titleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBarMousePressed

        // TODO add your handling code here:
    }//GEN-LAST:event_titleBarMousePressed

    private void titleBarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBarMouseEntered
        titleBar.setBackground(Color.BLACK);

    }//GEN-LAST:event_titleBarMouseEntered

    private void titleBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBarMouseClicked
      if(page==0)
      {
          gif.jLabelXLeft(0,-890, 10, 10, background);
      gif.jLabelXLeft(890,0, 10, 10, background1);
      page =1;
      titleBar.setText("Prev Page");}
      else
          if(page==1)
          {gif.jLabelXRight(-890,0, 10, 10, background);
      gif.jLabelXRight(0,890, 10, 10, background1);
       page=0;
          titleBar.setText("Next Page");}
    }//GEN-LAST:event_titleBarMouseClicked

    private void stopwatchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopwatchMouseClicked
if(page==0)
{myStopwatch obj = new myStopwatch();
     obj.show();}
else
    if(page==1)
    {   Main GIF = new Main();
    GIF.runMP3Player();
    }
     
    }//GEN-LAST:event_stopwatchMouseClicked

    private void historyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyMouseEntered
                history_1.setVisible(true);
        history_2.setVisible(true);
        history_3.setVisible(true);
        history_4.setVisible(true);
        
    }//GEN-LAST:event_historyMouseEntered

    private void aboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseEntered
              aboutDev.setVisible(true);
        credit.setVisible(true);
        version.setVisible(true);
        help.setVisible(true);
    }//GEN-LAST:event_aboutMouseEntered

    private void historyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyMouseExited
             
    }//GEN-LAST:event_historyMouseExited

    private void background1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_background1MouseEntered
       history_1.setVisible(false);
        history_2.setVisible(false);
        history_3.setVisible(false);
        history_4.setVisible(false);
        aboutDev.setVisible(false);
        credit.setVisible(false);
        version.setVisible(false);
        help.setVisible(false);
    }//GEN-LAST:event_background1MouseEntered

    private void background2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_background2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_background2MouseEntered

    private void calculatorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculatorMouseClicked
DisplayTrayIcon .trayIcon.displayMessage("Notice", "Not Available In Demo Version", TrayIcon.MessageType.INFO);                 
                
    }//GEN-LAST:event_calculatorMouseClicked

    private void memoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memoMouseClicked
             DisplayTrayIcon .trayIcon.displayMessage("Notice", "Not Available In Demo Version", TrayIcon.MessageType.INFO); 
    }//GEN-LAST:event_memoMouseClicked

    private void convertorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convertorMouseClicked
                DisplayTrayIcon .trayIcon.displayMessage("Notice", "Not Available In Demo Version", TrayIcon.MessageType.INFO); 
    }//GEN-LAST:event_convertorMouseClicked

    private void history_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_history_1MouseClicked
         
    }//GEN-LAST:event_history_1MouseClicked

    private void timerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timerMouseClicked
            if(page==0)
{ Timerr obj = new Timerr();
     obj.show();}
else
    if(page==1)
    {   DisplayTrayIcon .trayIcon.displayMessage("Notice", "Not Available In Demo Version", TrayIcon.MessageType.INFO);
    }
    }//GEN-LAST:event_timerMouseClicked

    private void history_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_history_4MouseClicked
         CompleteHistory his = new CompleteHistory();
          his.show();
    }//GEN-LAST:event_history_4MouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(Apps.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked
 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Apps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Apps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Apps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Apps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Apps().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel about;
    private javax.swing.JLabel aboutDev;
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel calculator;
    private javax.swing.JLabel close;
    private javax.swing.JLabel convertor;
    private javax.swing.JLabel credit;
    private javax.swing.JLabel help;
    private javax.swing.JLabel history;
    private javax.swing.JLabel history_1;
    private javax.swing.JLabel history_2;
    private javax.swing.JLabel history_3;
    private javax.swing.JLabel history_4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel memo;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel stopwatch;
    private javax.swing.JLabel time_1;
    private javax.swing.JLabel timer;
    private javax.swing.JLabel titleBar;
    private javax.swing.JLabel version;
    // End of variables declaration//GEN-END:variables
}
