/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home_package;

import classes.Starter;
import java.awt.TrayIcon;

/**
 *
 * @author Guest
 */
public class EnterPassword extends javax.swing.JFrame {
int count;
int buttonPressed;
int code1;
int code2;
int code3;
int code4;
String recheak;
int Recheck;
Starter GIF = new Starter();
     String cheak ;
     DisplayTrayIcon dwt = new DisplayTrayIcon();
    public EnterPassword() {
        initComponents();
      
    }
public void circleControl() 
      {count++;
      
      switch(count)
      {
          case 1: 
           
              code1= buttonPressed;
              password.setText(""+code1);
              
              break;
              
          case 2: 
            
              code2= buttonPressed;
              password.setText(""+code1+""+code2);
              break;
                  
             
          case 3: 
            
              code3= buttonPressed;
               password.setText(""+code1+""+code2+""+code3);
              break;
                    
                  
          case 4: 
              
              code4= buttonPressed;
              password.setText(""+code1+""+code2+""+code3+""+code4);
              count=0;
              if(Recheck==0)
              {cheak = code1 + "" +code2 + "" +code3 + "" +code4;
              
                    Recheck =1;  
                    header1.setText("RE ENTER PASSWORD");
              }
          else
                  if(Recheck==1)
              {recheak = code1 + "" +code2 + "" +code3 + "" +code4;
           
            Recheck =0;  
                    if(cheak.equals(recheak))
                    {DisplayTrayIcon .trayIcon.displayMessage(" ", "Password Save", TrayIcon.MessageType.INFO);
                   LockscreenGUI lock = new LockscreenGUI();
                   GIF.updatePWD(recheak);
                   lock.setVisible(true);
                         this.hide();
                   
                   break;
                    } 
                    else
                     if(cheak != recheak)
                    {DisplayTrayIcon .trayIcon.displayMessage(" ", "Password Not Verified", TrayIcon.MessageType.WARNING);
                    header1.setText("ENTER PASSWORD");
                   break;
                    }   
                   
              }
         
              
      }
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button0 = new javax.swing.JLabel();
        Button9 = new javax.swing.JLabel();
        Button8 = new javax.swing.JLabel();
        Button7 = new javax.swing.JLabel();
        Button6 = new javax.swing.JLabel();
        Button5 = new javax.swing.JLabel();
        Button4 = new javax.swing.JLabel();
        Button3 = new javax.swing.JLabel();
        Button2 = new javax.swing.JLabel();
        Button1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lsb = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        lsb1 = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        header1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(289, 460));
        setMinimumSize(new java.awt.Dimension(289, 460));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(289, 460));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Button0MouseReleased(evt);
            }
        });
        getContentPane().add(Button0, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 342, 60, 60));

        Button9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Button9MouseReleased(evt);
            }
        });
        getContentPane().add(Button9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 60, 60));

        Button8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Button8MouseReleased(evt);
            }
        });
        getContentPane().add(Button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 270, 60, 60));

        Button7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Button7MouseReleased(evt);
            }
        });
        getContentPane().add(Button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 270, 60, 60));

        Button6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Button6MouseReleased(evt);
            }
        });
        getContentPane().add(Button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 199, 60, 60));

        Button5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Button5MouseReleased(evt);
            }
        });
        getContentPane().add(Button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 199, 60, 60));

        Button4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Button4MouseReleased(evt);
            }
        });
        getContentPane().add(Button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 199, 60, 60));

        Button3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Button3MouseReleased(evt);
            }
        });
        getContentPane().add(Button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 60, 60));

        Button2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Button2MouseReleased(evt);
            }
        });
        getContentPane().add(Button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 130, 60, 60));

        Button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Button1MouseReleased(evt);
            }
        });
        getContentPane().add(Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 130, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/numbers.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 295, 290));

        lsb.setBackground(new java.awt.Color(51, 51, 51));
        lsb.setFont(new java.awt.Font("DS-Digital", 1, 18)); // NOI18N
        lsb.setForeground(new java.awt.Color(0, 168, 255));
        lsb.setOpaque(true);
        getContentPane().add(lsb, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 460));

        header.setBackground(new java.awt.Color(51, 51, 51));
        header.setFont(new java.awt.Font("DS-Digital", 1, 14)); // NOI18N
        header.setForeground(new java.awt.Color(0, 168, 255));
        header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.setOpaque(true);
        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 290, 30));

        lsb1.setBackground(new java.awt.Color(51, 51, 51));
        lsb1.setFont(new java.awt.Font("DS-Digital", 1, 18)); // NOI18N
        lsb1.setForeground(new java.awt.Color(0, 168, 255));
        lsb1.setOpaque(true);
        getContentPane().add(lsb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 20, 460));

        password.setBackground(new java.awt.Color(51, 51, 51));
        password.setFont(new java.awt.Font("DS-Digital", 1, 14)); // NOI18N
        password.setForeground(new java.awt.Color(0, 168, 255));
        password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        password.setOpaque(true);
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 150, 30));

        header1.setBackground(new java.awt.Color(51, 51, 51));
        header1.setFont(new java.awt.Font("DS-Digital", 1, 14)); // NOI18N
        header1.setForeground(new java.awt.Color(0, 168, 255));
        header1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header1.setText("enter password");
        header1.setOpaque(true);
        getContentPane().add(header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 30));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 250, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     
   
    }//GEN-LAST:event_formWindowOpened

    private void Button0MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button0MouseReleased
        buttonPressed=0;
        circleControl();
        // TODO add your handling code here:
    }//GEN-LAST:event_Button0MouseReleased

    private void Button9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button9MouseReleased
        buttonPressed=9;
        circleControl();
        // TODO add your handling code here:
    }//GEN-LAST:event_Button9MouseReleased

    private void Button8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button8MouseReleased
        buttonPressed=8;
        circleControl();
        // TODO add your handling code here:
    }//GEN-LAST:event_Button8MouseReleased

    private void Button7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button7MouseReleased
        buttonPressed=7;
        circleControl();
        // TODO add your handling code here:
    }//GEN-LAST:event_Button7MouseReleased

    private void Button6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button6MouseReleased
        buttonPressed=6;
        circleControl();
        // TODO add your handling code here:
    }//GEN-LAST:event_Button6MouseReleased

    private void Button5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button5MouseReleased

        buttonPressed=5;
        circleControl();
        // TODO add your handling code here:
    }//GEN-LAST:event_Button5MouseReleased

    private void Button4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button4MouseReleased
        buttonPressed=4;
        circleControl();
        // TODO add your handling code here:
    }//GEN-LAST:event_Button4MouseReleased

    private void Button3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button3MouseReleased
        buttonPressed=3;
        circleControl();

    }//GEN-LAST:event_Button3MouseReleased

    private void Button2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button2MouseReleased
        buttonPressed=2;
        circleControl();

    }//GEN-LAST:event_Button2MouseReleased

    private void Button1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button1MouseReleased
        buttonPressed=1;
        circleControl();

    }//GEN-LAST:event_Button1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnterPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Button0;
    private javax.swing.JLabel Button1;
    private javax.swing.JLabel Button2;
    private javax.swing.JLabel Button3;
    private javax.swing.JLabel Button4;
    private javax.swing.JLabel Button5;
    private javax.swing.JLabel Button6;
    private javax.swing.JLabel Button7;
    private javax.swing.JLabel Button8;
    private javax.swing.JLabel Button9;
    private javax.swing.JLabel header;
    private javax.swing.JLabel header1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lsb;
    private javax.swing.JLabel lsb1;
    private javax.swing.JLabel password;
    // End of variables declaration//GEN-END:variables
}
