/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home_package;


import AppPackage.AnimationClass;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Color;
import java.awt.TrayIcon;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import widgetlauncher.GoogleSearch;
/**
 *
 * @author Guest
 */
public class Home_page extends javax.swing.JFrame {
  DisplayTrayIcon dwt = new DisplayTrayIcon();
  int xMouse;
  int yMouse;
     AnimationClass gif = new AnimationClass();
    public Home_page() {
        initComponents();
        
        display();
        clock clo = new clock();
        clo.time(time_1,jLabel1);
        clo.date(daydate);
        
    }
 
 public void display()
 {new Thread(){
public void run(){     
while(true)
 { if(deadline.getY() == 410)
 { taskh.setVisible(true);
        jScrollPane1.setVisible(true);
        hline.setVisible(true);
        vline.setVisible(true);
        vline1.setVisible(true);
  day.setVisible(true);
   month.setVisible(true);
   year.setVisible(true);
 add.setVisible(true);
 add1.setVisible(true);}
  if(deadline.getY()>410)
 { taskh.setVisible(false);
        jScrollPane1.setVisible(false);
        hline.setVisible(false);
        vline.setVisible(false);
        vline1.setVisible(false);
 day.setVisible(false);
   month.setVisible(false);
   year.setVisible(false);
 add.setVisible(false);
 add1.setVisible(false);}
 
 }}}.start();
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        about = new javax.swing.JLabel();
        aboutDev = new javax.swing.JLabel();
        credit = new javax.swing.JLabel();
        version = new javax.swing.JLabel();
        help = new javax.swing.JLabel();
        history = new javax.swing.JLabel();
        history_3 = new javax.swing.JLabel();
        history_4 = new javax.swing.JLabel();
        history_1 = new javax.swing.JLabel();
        history_2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        settings = new javax.swing.JLabel();
        application = new javax.swing.JLabel();
        daydate = new javax.swing.JLabel();
        manager = new javax.swing.JLabel();
        games = new javax.swing.JLabel();
        time_1 = new javax.swing.JLabel();
        deadline = new javax.swing.JLabel();
        minimize1 = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        taskh = new javax.swing.JTextField();
        vline1 = new javax.swing.JLabel();
        vline = new javax.swing.JLabel();
        hline = new javax.swing.JLabel();
        year = new javax.swing.JComboBox();
        month = new javax.swing.JComboBox();
        day = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        add1 = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        deadlineBg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(820, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(820, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        about.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutMouseEntered(evt);
            }
        });
        getContentPane().add(about);
        about.setBounds(220, 10, 90, 30);

        aboutDev.setBackground(java.awt.Color.darkGray);
        aboutDev.setFont(new java.awt.Font("DS-Digital", 0, 12)); // NOI18N
        aboutDev.setForeground(new java.awt.Color(0, 168, 255));
        aboutDev.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutDev.setText("developers");
        aboutDev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutDev.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        aboutDev.setOpaque(true);
        aboutDev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutDevMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutDevMouseExited(evt);
            }
        });
        getContentPane().add(aboutDev);
        aboutDev.setBounds(230, 40, 130, 30);

        credit.setBackground(java.awt.Color.darkGray);
        credit.setFont(new java.awt.Font("DS-Digital", 0, 12)); // NOI18N
        credit.setForeground(new java.awt.Color(0, 168, 255));
        credit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        credit.setText("credits");
        credit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        credit.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        credit.setOpaque(true);
        credit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                creditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                creditMouseExited(evt);
            }
        });
        getContentPane().add(credit);
        credit.setBounds(230, 70, 130, 30);

        version.setBackground(java.awt.Color.darkGray);
        version.setFont(new java.awt.Font("DS-Digital", 0, 12)); // NOI18N
        version.setForeground(new java.awt.Color(0, 168, 255));
        version.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        version.setText("version");
        version.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        version.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        version.setOpaque(true);
        version.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                versionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                versionMouseExited(evt);
            }
        });
        getContentPane().add(version);
        version.setBounds(230, 100, 130, 30);

        help.setBackground(java.awt.Color.darkGray);
        help.setFont(new java.awt.Font("DS-Digital", 0, 12)); // NOI18N
        help.setForeground(new java.awt.Color(0, 168, 255));
        help.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        help.setText("help");
        help.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        help.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        help.setOpaque(true);
        help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                helpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                helpMouseExited(evt);
            }
        });
        getContentPane().add(help);
        help.setBounds(230, 130, 130, 30);

        history.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        history.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                historyMouseEntered(evt);
            }
        });
        getContentPane().add(history);
        history.setBounds(90, 10, 90, 30);

        history_3.setBackground(java.awt.Color.darkGray);
        history_3.setFont(new java.awt.Font("DS-Digital", 0, 12)); // NOI18N
        history_3.setForeground(new java.awt.Color(0, 168, 255));
        history_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        history_3.setText("<No History>");
        history_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        history_3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        history_3.setOpaque(true);
        history_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                history_3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                history_3MouseExited(evt);
            }
        });
        getContentPane().add(history_3);
        history_3.setBounds(90, 100, 130, 30);

        history_4.setBackground(java.awt.Color.darkGray);
        history_4.setFont(new java.awt.Font("DS-Digital", 0, 12)); // NOI18N
        history_4.setForeground(new java.awt.Color(0, 168, 255));
        history_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        history_4.setText("Complete History");
        history_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        history_4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        history_4.setOpaque(true);
        history_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                history_4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                history_4MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                history_4MouseReleased(evt);
            }
        });
        getContentPane().add(history_4);
        history_4.setBounds(90, 130, 130, 30);

        history_1.setBackground(java.awt.Color.darkGray);
        history_1.setFont(new java.awt.Font("DS-Digital", 0, 12)); // NOI18N
        history_1.setForeground(new java.awt.Color(0, 168, 255));
        history_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        history_1.setText("<No History>");
        history_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        history_1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        history_1.setOpaque(true);
        history_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                history_1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                history_1MouseExited(evt);
            }
        });
        getContentPane().add(history_1);
        history_1.setBounds(90, 40, 130, 30);

        history_2.setBackground(java.awt.Color.darkGray);
        history_2.setFont(new java.awt.Font("DS-Digital", 0, 12)); // NOI18N
        history_2.setForeground(new java.awt.Color(0, 168, 255));
        history_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        history_2.setText("<No History>");
        history_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        history_2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        history_2.setOpaque(true);
        history_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                history_2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                history_2MouseExited(evt);
            }
        });
        getContentPane().add(history_2);
        history_2.setBounds(90, 70, 130, 30);

        jTextField1.setBackground(new java.awt.Color(51, 51, 51));
        jTextField1.setForeground(new java.awt.Color(0, 168, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Search");
        jTextField1.setBorder(null);
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.setFocusable(false);
        jTextField1.setOpaque(false);
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(490, 120, 240, 30);

        settings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                settingsMouseReleased(evt);
            }
        });
        getContentPane().add(settings);
        settings.setBounds(230, 270, 120, 130);

        application.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        application.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                applicationMouseReleased(evt);
            }
        });
        getContentPane().add(application);
        application.setBounds(70, 270, 120, 130);

        daydate.setFont(new java.awt.Font("DS-Digital", 1, 24)); // NOI18N
        daydate.setForeground(new java.awt.Color(0, 168, 255));
        daydate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(daydate);
        daydate.setBounds(450, 290, 340, 50);

        manager.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(manager);
        manager.setBounds(230, 110, 120, 130);

        games.setForeground(new java.awt.Color(0, 168, 255));
        games.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        games.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gamesMouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                gamesMouseReleased(evt);
            }
        });
        getContentPane().add(games);
        games.setBounds(70, 110, 120, 130);

        time_1.setFont(new java.awt.Font("DS-Digital", 1, 60)); // NOI18N
        time_1.setForeground(new java.awt.Color(0, 168, 255));
        time_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(time_1);
        time_1.setBounds(450, 200, 340, 120);

        deadline.setBackground(new java.awt.Color(0, 0, 0));
        deadline.setFont(new java.awt.Font("DS-Digital", 1, 18)); // NOI18N
        deadline.setForeground(new java.awt.Color(0, 168, 255));
        deadline.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deadline.setText("TASK'S DEADLINE");
        deadline.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deadline.setOpaque(true);
        deadline.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deadlineMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deadlineMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deadlineMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                deadlineMouseReleased(evt);
            }
        });
        getContentPane().add(deadline);
        deadline.setBounds(80, 570, 310, 30);

        minimize1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize1MouseClicked(evt);
            }
        });
        getContentPane().add(minimize1);
        minimize1.setBounds(760, 10, 20, 20);

        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize);
        minimize.setBounds(710, 10, 30, 20);

        taskh.setFont(new java.awt.Font("DS-Digital", 1, 14)); // NOI18N
        taskh.setForeground(new java.awt.Color(0, 168, 255));
        taskh.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        taskh.setText("Task Headline");
        taskh.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(taskh);
        taskh.setBounds(90, 450, 140, 30);

        vline1.setBackground(new java.awt.Color(0, 240, 240));
        vline1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        vline1.setOpaque(true);
        getContentPane().add(vline1);
        vline1.setBounds(330, 450, 2, 120);

        vline.setBackground(new java.awt.Color(0, 240, 240));
        vline.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        vline.setOpaque(true);
        getContentPane().add(vline);
        vline.setBounds(240, 450, 2, 120);

        hline.setBackground(new java.awt.Color(0, 240, 240));
        hline.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        hline.setOpaque(true);
        getContentPane().add(hline);
        hline.setBounds(90, 490, 150, 2);

        year.setBackground(new java.awt.Color(0, 0, 0));
        year.setEditable(true);
        year.setFont(new java.awt.Font("DS-Digital", 1, 14)); // NOI18N
        year.setForeground(new java.awt.Color(0, 168, 255));
        year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "YEAR", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024" }));
        year.setToolTipText("Year");
        year.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        year.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        year.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        year.setMinimumSize(new java.awt.Dimension(37, 30));
        year.setOpaque(false);
        year.setPreferredSize(new java.awt.Dimension(37, 30));
        getContentPane().add(year);
        year.setBounds(250, 530, 70, 30);

        month.setBackground(new java.awt.Color(0, 0, 0));
        month.setEditable(true);
        month.setFont(new java.awt.Font("DS-Digital", 1, 14)); // NOI18N
        month.setForeground(new java.awt.Color(0, 168, 255));
        month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC" }));
        month.setToolTipText("Month");
        month.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        month.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        month.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        month.setMinimumSize(new java.awt.Dimension(37, 30));
        month.setOpaque(false);
        month.setPreferredSize(new java.awt.Dimension(37, 30));
        getContentPane().add(month);
        month.setBounds(250, 490, 70, 30);

        day.setBackground(new java.awt.Color(0, 0, 0));
        day.setEditable(true);
        day.setFont(new java.awt.Font("DS-Digital", 1, 14)); // NOI18N
        day.setForeground(new java.awt.Color(0, 168, 255));
        day.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DAY", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        day.setToolTipText("Day");
        day.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        day.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        day.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        day.setMinimumSize(new java.awt.Dimension(37, 30));
        day.setName(""); // NOI18N
        day.setPreferredSize(new java.awt.Dimension(37, 30));
        getContentPane().add(day);
        day.setBounds(250, 450, 70, 30);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        description.setColumns(20);
        description.setFont(new java.awt.Font("DS-Digital", 0, 18)); // NOI18N
        description.setForeground(new java.awt.Color(0, 168, 255));
        description.setLineWrap(true);
        description.setRows(5);
        description.setText("<DESCRIPTION>");
        description.setWrapStyleWord(true);
        description.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(description);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 500, 140, 60);

        add1.setBackground(java.awt.Color.darkGray);
        add1.setFont(new java.awt.Font("DS-Digital", 1, 18)); // NOI18N
        add1.setForeground(new java.awt.Color(0, 168, 255));
        add1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add1.setText("open");
        add1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add1.setOpaque(true);
        add1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add1MouseExited(evt);
            }
        });
        getContentPane().add(add1);
        add1.setBounds(340, 510, 50, 40);

        add.setBackground(java.awt.Color.darkGray);
        add.setFont(new java.awt.Font("DS-Digital", 1, 18)); // NOI18N
        add.setForeground(new java.awt.Color(0, 168, 255));
        add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add.setText("ADD");
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.setOpaque(true);
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        getContentPane().add(add);
        add.setBounds(340, 460, 50, 40);

        deadlineBg.setBackground(java.awt.Color.darkGray);
        deadlineBg.setOpaque(true);
        getContentPane().add(deadlineBg);
        deadlineBg.setBounds(80, 600, 310, 170);

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(530, 530, 230, 20);

        background.setBackground(new java.awt.Color(0, 0, 0));
        background.setFont(new java.awt.Font("DS-Digital", 0, 12)); // NOI18N
        background.setForeground(new java.awt.Color(0, 168, 255));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Picture4.png"))); // NOI18N
        background.setText("testing");
        background.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        background.setMaximumSize(new java.awt.Dimension(820, 600));
        background.setMinimumSize(new java.awt.Dimension(820, 600));
        background.setOpaque(true);
        background.setPreferredSize(new java.awt.Dimension(820, 600));
        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backgroundMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backgroundMousePressed(evt);
            }
        });
        background.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                backgroundMouseDragged(evt);
            }
        });
        getContentPane().add(background);
        background.setBounds(0, 0, 820, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
  
   history obj = new history("Home Page");
   obj.addHistory();
   History_set god = new History_set();
   god.setHistory(history_1,history_2,history_3);
   history_1.setVisible(false);
   history_2.setVisible(false);
   history_3.setVisible(false);
   history_4.setVisible(false);
    aboutDev.setVisible(false);
   credit.setVisible(false);
   version.setVisible(false);
   help.setVisible(false);
   day.setVisible(false);
   month.setVisible(false);
   year.setVisible(false);
    taskh.setVisible(false);
   jScrollPane1.setVisible(false);
        hline.setVisible(false);
        vline.setVisible(false);
        vline1.setVisible(false);
        add.setVisible(false);
        add1.setVisible(false);
   
    }//GEN-LAST:event_formWindowOpened

    private void gamesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gamesMouseEntered
      
    }//GEN-LAST:event_gamesMouseEntered

    private void historyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyMouseEntered
     history_1.setVisible(true);
   history_2.setVisible(true);
   history_3.setVisible(true);
   history_4.setVisible(true);
    }//GEN-LAST:event_historyMouseEntered

    private void history_1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_history_1MouseEntered
    history_1.setBackground(Color.BLACK);
    }//GEN-LAST:event_history_1MouseEntered

    private void history_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_history_1MouseExited
     history_1.setBackground(Color.DARK_GRAY);
     
    }//GEN-LAST:event_history_1MouseExited

    private void history_2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_history_2MouseEntered
        history_2.setBackground(Color.BLACK);
    }//GEN-LAST:event_history_2MouseEntered

    private void history_3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_history_3MouseEntered
history_3.setBackground(Color.BLACK);        // TODO add your handling code here:
    }//GEN-LAST:event_history_3MouseEntered

    private void history_4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_history_4MouseEntered
        history_4.setBackground(Color.BLACK);
    }//GEN-LAST:event_history_4MouseEntered

    private void history_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_history_2MouseExited
 history_2.setBackground(Color.DARK_GRAY);        // TODO add your handling code here:
    }//GEN-LAST:event_history_2MouseExited

    private void history_3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_history_3MouseExited
history_3.setBackground(Color.DARK_GRAY);         // TODO add your handling code here:
    }//GEN-LAST:event_history_3MouseExited

    private void history_4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_history_4MouseExited
history_4.setBackground(Color.DARK_GRAY);         // TODO add your handling code here:
    }//GEN-LAST:event_history_4MouseExited

    private void backgroundMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseEntered
        history_1.setVisible(false);
   history_2.setVisible(false);
   history_3.setVisible(false);
   history_4.setVisible(false);
    aboutDev.setVisible(false);
   credit.setVisible(false);
   version.setVisible(false);
   help.setVisible(false);
    }//GEN-LAST:event_backgroundMouseEntered

    private void deadlineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deadlineMouseClicked
        if(deadline.getY() == 410)
        { 
            jScrollPane1.setVisible(false);
         hline.setVisible(false);
        vline.setVisible(false);
        vline1.setVisible(false);
        gif.jLabelYDown(410,570,20,5,deadline);
        gif.jLabelYDown(435,600,20,5,deadlineBg);
    
      
     
       
      
        deadline.setBackground(Color.BLACK);
        }
        else
        if(deadline.getY() == 570)
        {AnimationClass gif = new AnimationClass();
        gif.jLabelYUp(570,410,20,5,deadline);
        gif.jLabelYUp(600,435,20,5,deadlineBg);
     

               
        deadline.setBackground(Color.DARK_GRAY);}
    }//GEN-LAST:event_deadlineMouseClicked

    private void deadlineMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deadlineMousePressed
        
// TODO add your handling code here:
    }//GEN-LAST:event_deadlineMousePressed

    private void deadlineMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deadlineMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_deadlineMouseReleased

    private void deadlineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deadlineMouseEntered
     deadline.setBackground(Color.BLACK);
      
        
    }//GEN-LAST:event_deadlineMouseEntered

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
     add.setBackground(Color.BLACK);
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
         add.setBackground(Color.DARK_GRAY); // TODO add your handling code here:
    }//GEN-LAST:event_addMouseExited

    private void minimize1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize1MouseClicked
int res = JOptionPane.showConfirmDialog(null, "Do You Want To Exit");
if(res ==0)
        System.exit(0);
    }//GEN-LAST:event_minimize1MouseClicked

    private void aboutDevMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutDevMouseEntered
       aboutDev.setBackground(Color.BLACK);
    }//GEN-LAST:event_aboutDevMouseEntered

    private void aboutDevMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutDevMouseExited
         aboutDev.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_aboutDevMouseExited

    private void creditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditMouseEntered
          credit.setBackground(Color.BLACK);
    }//GEN-LAST:event_creditMouseEntered

    private void creditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditMouseExited
      credit.setBackground(Color.DARK_GRAY);  // TODO add your handling code here:
    }//GEN-LAST:event_creditMouseExited

    private void versionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_versionMouseEntered
        version.setBackground(Color.BLACK);
    }//GEN-LAST:event_versionMouseEntered

    private void versionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_versionMouseExited
      version.setBackground(Color.DARK_GRAY);  // TODO add your handling code here:
    }//GEN-LAST:event_versionMouseExited

    private void helpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMouseEntered
      help.setBackground(Color.BLACK);  // TODO add your handling code here:
    }//GEN-LAST:event_helpMouseEntered

    private void helpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMouseExited
      help.setBackground(Color.DARK_GRAY);  // TODO add your handling code here:
    }//GEN-LAST:event_helpMouseExited

    private void aboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseEntered
        aboutDev.setVisible(true);
   credit.setVisible(true);
   version.setVisible(true);
   help.setVisible(true);
    }//GEN-LAST:event_aboutMouseEntered

    private void add1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add1MouseEntered
     add1.setBackground(Color.BLACK);
    }//GEN-LAST:event_add1MouseEntered

    private void add1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add1MouseExited
      add1.setBackground(Color.DARK_GRAY);  // TODO add your handling code here:
    }//GEN-LAST:event_add1MouseExited

    private void backgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMousePressed
    xMouse = evt.getX();
    yMouse = evt.getY();
    }//GEN-LAST:event_backgroundMousePressed

    private void backgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseDragged
   int x = evt.getXOnScreen();
   int y = evt.getYOnScreen();
   
   this.setLocation(x- xMouse, y - yMouse);
    }//GEN-LAST:event_backgroundMouseDragged

    private void applicationMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applicationMouseReleased
  Apps apps = new Apps();
  apps.show();
    }//GEN-LAST:event_applicationMouseReleased

    private void history_4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_history_4MouseReleased
           CompleteHistory his = new CompleteHistory();
          his.show();
    }//GEN-LAST:event_history_4MouseReleased

    private void gamesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gamesMouseReleased
         DisplayTrayIcon .trayIcon.displayMessage("Notice", "Not Available In Demo Version", TrayIcon.MessageType.INFO); 
    }//GEN-LAST:event_gamesMouseReleased

    private void settingsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseReleased
             DisplayTrayIcon .trayIcon.displayMessage("Notice", "Not Available In Demo Version", TrayIcon.MessageType.INFO); 
    }//GEN-LAST:event_settingsMouseReleased

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
       DisplayTrayIcon .trayIcon.displayMessage("Notice", "Not Available In Demo Version", TrayIcon.MessageType.INFO); 
    }//GEN-LAST:event_jLabel2MouseReleased

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
         DisplayTrayIcon .trayIcon.displayMessage("Notice", "Not Available In Demo Version", TrayIcon.MessageType.INFO); 
    }//GEN-LAST:event_jTextField1MouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
           try{
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection) 
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/abd","root","root");
        Statement stmt = (Statement)con.createStatement();
       String headline = taskh.getText();
       String desc = description.getText();
       int day1 = day.getSelectedIndex();
       int month1 = month.getSelectedIndex();
     String year1 = (String) year.getSelectedItem();
     if(day1==0 || month1 == 0 || year1.equals("year"))
     {JOptionPane.showMessageDialog(null,"Pls insert date properly....");
     }
     else
     {
   String date1 = year1 + "-"+ month1 + "-" + day1;
   String query = "Insert into task values('"+headline+"','"+desc+"','"+date1+"');";
            int rs2 = stmt.executeUpdate(query);
     JOptionPane.showMessageDialog(null,"Task '"+ headline+"' Added");
     }  }
        catch(Exception e)
        {JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_addMouseClicked

    private void add1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add1MouseClicked
       try
        {String headline = taskh.getText();
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection) 
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/abd","root","root");
        Statement stmt = (Statement)con.createStatement();
        String task = "Select * from task where title = '"+headline+ "';";
     
           ResultSet rs = stmt.executeQuery(task);
     while(rs.next())
        {description.setText(rs.getString("description"));
       description.append("\n Deadline: "+ rs.getString("deadline"));
        }
     }
           
           catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
           
    }//GEN-LAST:event_add1MouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
    this.setState(Home_page.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked
 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel about;
    private javax.swing.JLabel aboutDev;
    private javax.swing.JLabel add;
    private javax.swing.JLabel add1;
    private javax.swing.JLabel application;
    private javax.swing.JLabel background;
    private javax.swing.JLabel credit;
    private javax.swing.JComboBox day;
    private javax.swing.JLabel daydate;
    private javax.swing.JLabel deadline;
    private javax.swing.JLabel deadlineBg;
    private javax.swing.JTextArea description;
    private javax.swing.JLabel games;
    private javax.swing.JLabel help;
    private javax.swing.JLabel history;
    private javax.swing.JLabel history_1;
    private javax.swing.JLabel history_2;
    private javax.swing.JLabel history_3;
    private javax.swing.JLabel history_4;
    private javax.swing.JLabel hline;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel manager;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel minimize1;
    private javax.swing.JComboBox month;
    private javax.swing.JLabel settings;
    private javax.swing.JTextField taskh;
    private javax.swing.JLabel time_1;
    private javax.swing.JLabel version;
    private javax.swing.JLabel vline;
    private javax.swing.JLabel vline1;
    private javax.swing.JComboBox year;
    // End of variables declaration//GEN-END:variables
}
