/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home_package;

import java.awt.Color;

/**
 *
 * @author Guest
 */
public class myStopwatch extends javax.swing.JFrame {

    int xMouse;
    int yMouse;
     history obj = new history("StopWatch");
   
    public myStopwatch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        degree1 = new javax.swing.JLabel();
        mlb = new javax.swing.JLabel();
        rlb = new javax.swing.JLabel();
        rsb = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        bb = new javax.swing.JLabel();
        lsb = new javax.swing.JLabel();
        head = new javax.swing.JLabel();
        llb = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 310));
        setMinimumSize(new java.awt.Dimension(500, 310));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 310));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        degree1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        degree1.setForeground(new java.awt.Color(255, 255, 255));
        degree1.setText("X");
        degree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                degree1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                degree1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                degree1MouseExited(evt);
            }
        });
        getContentPane().add(degree1);
        degree1.setBounds(470, 0, 20, 30);

        mlb.setBackground(new java.awt.Color(0, 0, 0));
        mlb.setFont(new java.awt.Font("DS-Digital", 1, 18)); // NOI18N
        mlb.setForeground(new java.awt.Color(0, 168, 255));
        mlb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mlb.setText("stop");
        mlb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mlb.setOpaque(true);
        mlb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mlbMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mlbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mlbMouseExited(evt);
            }
        });
        getContentPane().add(mlb);
        mlb.setBounds(220, 220, 50, 40);

        rlb.setBackground(new java.awt.Color(0, 0, 0));
        rlb.setFont(new java.awt.Font("DS-Digital", 1, 18)); // NOI18N
        rlb.setForeground(new java.awt.Color(0, 168, 255));
        rlb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rlb.setText("reset");
        rlb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rlb.setOpaque(true);
        rlb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rlbMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rlbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rlbMouseExited(evt);
            }
        });
        getContentPane().add(rlb);
        rlb.setBounds(390, 220, 50, 40);

        rsb.setBackground(new java.awt.Color(51, 51, 51));
        rsb.setFont(new java.awt.Font("DS-Digital", 1, 18)); // NOI18N
        rsb.setForeground(new java.awt.Color(0, 168, 255));
        rsb.setOpaque(true);
        getContentPane().add(rsb);
        rsb.setBounds(490, 20, 10, 270);

        header.setBackground(new java.awt.Color(51, 51, 51));
        header.setFont(new java.awt.Font("DS-Digital", 1, 18)); // NOI18N
        header.setForeground(new java.awt.Color(0, 168, 255));
        header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.setText("STOPWATCH");
        header.setOpaque(true);
        getContentPane().add(header);
        header.setBounds(0, 0, 500, 29);

        bb.setBackground(new java.awt.Color(51, 51, 51));
        bb.setFont(new java.awt.Font("DS-Digital", 1, 18)); // NOI18N
        bb.setForeground(new java.awt.Color(0, 168, 255));
        bb.setOpaque(true);
        getContentPane().add(bb);
        bb.setBounds(0, 290, 500, 20);

        lsb.setBackground(new java.awt.Color(51, 51, 51));
        lsb.setFont(new java.awt.Font("DS-Digital", 1, 18)); // NOI18N
        lsb.setForeground(new java.awt.Color(0, 168, 255));
        lsb.setOpaque(true);
        getContentPane().add(lsb);
        lsb.setBounds(0, 20, 10, 270);

        head.setBackground(new java.awt.Color(0, 0, 0));
        head.setFont(new java.awt.Font("DS-Digital", 1, 48)); // NOI18N
        head.setForeground(new java.awt.Color(0, 168, 255));
        head.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        head.setText("00:0:0:0");
        head.setOpaque(true);
        getContentPane().add(head);
        head.setBounds(50, 50, 380, 150);

        llb.setBackground(new java.awt.Color(0, 0, 0));
        llb.setFont(new java.awt.Font("DS-Digital", 1, 18)); // NOI18N
        llb.setForeground(new java.awt.Color(0, 168, 255));
        llb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        llb.setText("Start");
        llb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        llb.setOpaque(true);
        llb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                llbMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                llbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                llbMouseExited(evt);
            }
        });
        getContentPane().add(llb);
        llb.setBounds(50, 220, 50, 40);

        background.setBackground(new java.awt.Color(0, 0, 0));
        background.setOpaque(true);
        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backgroundMousePressed(evt);
            }
        });
        background.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                backgroundMouseDragged(evt);
            }
        });
        getContentPane().add(background);
        background.setBounds(0, 0, 500, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void llbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llbMouseEntered
   llb.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_llbMouseEntered

    private void llbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llbMouseExited
     llb.setBackground(Color.BLACK);
    }//GEN-LAST:event_llbMouseExited

    private void mlbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mlbMouseEntered
        mlb.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_mlbMouseEntered

    private void mlbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mlbMouseExited
       mlb.setBackground(Color.BLACK); // TODO add your handling code here:
    }//GEN-LAST:event_mlbMouseExited

    private void rlbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rlbMouseEntered
       rlb.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_rlbMouseEntered

    private void rlbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rlbMouseExited
  rlb.setBackground(Color.BLACK);        // TODO add your handling code here:
    }//GEN-LAST:event_rlbMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
   
   obj.addHistory();
        this.setLocation(120, 60);
        mlb.setVisible(false);
       rlb.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void llbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llbMouseClicked
     stopwatch gif = new stopwatch();
       gif.startStopwatch(head, rlb);
       
       mlb.setVisible(true);
       llb.setEnabled(false);
    }//GEN-LAST:event_llbMouseClicked

    private void mlbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mlbMouseClicked
        rlb.setVisible(true);
    }//GEN-LAST:event_mlbMouseClicked

    private void rlbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rlbMouseClicked
        mlb.setVisible(false);
        head.setText("00:0:0:0");
        llb.setEnabled(true);
        rlb.setVisible(false);
    }//GEN-LAST:event_rlbMouseClicked

    private void backgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMousePressed
     xMouse = evt.getX();
     yMouse = evt.getY();
    }//GEN-LAST:event_backgroundMousePressed

    private void backgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseDragged
          int x = evt.getXOnScreen();
          int y = evt.getYOnScreen();
          
          this.setLocation(x- xMouse, y - yMouse);
    }//GEN-LAST:event_backgroundMouseDragged

    private void degree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_degree1MouseClicked
        this.hide();
    }//GEN-LAST:event_degree1MouseClicked

    private void degree1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_degree1MouseEntered
        degree1.setForeground(Color.red);
    }//GEN-LAST:event_degree1MouseEntered

    private void degree1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_degree1MouseExited
        degree1.setForeground(Color.WHITE);
    }//GEN-LAST:event_degree1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myStopwatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myStopwatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myStopwatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myStopwatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myStopwatch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel bb;
    private javax.swing.JLabel degree1;
    private javax.swing.JLabel head;
    private javax.swing.JLabel header;
    private javax.swing.JLabel llb;
    private javax.swing.JLabel lsb;
    private javax.swing.JLabel mlb;
    private javax.swing.JLabel rlb;
    private javax.swing.JLabel rsb;
    // End of variables declaration//GEN-END:variables
}
